### ISSUE TITLE
Info about project working

### ISSUE THREAD

**Issue by sahilihas** [Jonas-sebera/gamer-dao#1]
Hey, Jaz I want to know if this project working or not. because I face some issues in the project while running 
npx hardhat run scripts/AirDropV1/1_deploy_token.js --network testnet
command. error: HH8-> private key is too short.
Let me know if this project works or not in the end

**Comment by 0xJonaseb11** [comment]
Please ensure that your _environment variables_ **(specifically the private key)** are well configured and inform me later.. Otherwise, the project works smoothly.

**Comment by sahilihas** [comment]
Jaz, I still get this error. can you please tell me how I configured my private key properly? If there is any tutorial or doc available. Please refer it to me

**Comment by 0xJonaseb11** [comment]
Dear, Is the issue now resolved @sahilihas ??

**Comment by sahilihas** [comment]
not yet boss,  @Jaz-3-0  I still get this error. can you please tell me how I configured my private key properly? If there is any tutorial or doc available. Please refer it to me.

**Comment by 0xJonaseb11** [comment]
PLEASE note that your environment variables should be in this format below. 
```
PRIVATE_KEY=

QRC20_ADDRESS=

DAO_REGISTRY_ADDRESS=

AIRDROPV1_ADDRESS=

MODULE_IMPLEMENTATION=


MAIN_DAO_VOTING_ADDRESS =

VOTING_CONTRACT_ADDRESS =

MODULE_NAME = "AirDropV2"

DAO_REGISTRY_NAME = "DAO_REGISTRY"

TEN_PERCENTAGE = "100000000000000000000000000"

```

To learn more about the .env variables above, refer to Q Blockchain at [Q Blockchan documentation](https://docs.q.org/)

If you need further assistance please let me know - I'm here to help
Regards!

**Comment by sahilihas** [comment]
Thanks brooo, btw how can I contact you for further help and details?

**Comment by 0xJonaseb11** [comment]
For any help or consultancy dm me at **sebejaz99@gmail.com** or at [Linkedin](https://www.linkedin.com/in/sebera-jonas)

**Comment by 0xJonaseb11** [comment]
Issue closed as resolve on 4th April, 2024. **_CLOSED AS RESOLVED_**
